# Generated by Django 5.2.6 on 2025-12-02 19:46

import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_employer_fields'),
    ]

    # This migration has been converted to a no-op because the Resume-related
    # models were removed from the codebase. Leaving a no-op migration file
    # preserves migration ordering without attempting to recreate deleted models.
    operations = []
