# Generated by Django 5.2.6 on 2025-12-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_profile_picture'),
    ]
    # Migration removed: experience model was deleted; keep as no-op
    operations = []
