# Generated by Django 5.2.6 on 2025-12-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_experience_start_date'),
    ]
    # Migration removed: resume model was deleted; keep as no-op
    operations = []
