# Generated by Django 5.2.6 on 2025-12-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_resume_linkedin_alter_resume_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='education',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='skills',
        ),
    ]
