# Generated by Django 5.2.6 on 2025-12-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_jobseeker_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='bio',
            field=models.TextField(blank=True, help_text='Courte présentation'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='experience_years',
            field=models.IntegerField(blank=True, help_text="Années d'expérience", null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.CharField(blank=True, help_text='Compétences séparées par des virgules', max_length=500),
        ),
    ]
