# Generated by Django 5.2.9 on 2025-12-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_jobseeker_bio_jobseeker_experience_years_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='skills',
        ),
    ]
