# Generated by Django 5.2.6 on 2025-12-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('job_posted', 'Offre publiée'), ('job_applied', 'Candidature envoyée'), ('application_status', 'Statut de candidature modifié'), ('company_followed', 'Entreprise suivie'), ('profile_updated', 'Profil mis à jour')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('reviewing', 'En révision'), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('phone', 'Téléphone'), ('video', 'Visio'), ('in_person', 'Présentiel'), ('online', 'Test en ligne')], default='in_person', max_length=50),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Planifié'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('rescheduled', 'Replanifié')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_interview', 'Nouvel entretien'), ('interview_reminder', 'Rappel d’entretien'), ('application_status', 'Statut de candidature modifié'), ('new_application', 'Nouvelle candidature'), ('new_message', 'Nouveau message'), ('job_posted', 'Offre publiée'), ('job_updated', 'Offre mise à jour')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('application_deadline', 'Date limite de candidature'), ('interview', 'Entretien'), ('follow_up', 'Relance'), ('task', 'Tâche'), ('custom', 'Personnalisé')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute')], default='medium', max_length=20),
        ),
        migrations.DeleteModel(
            name='CompanyFollow',
        ),
    ]
