# Generated by Django 5.2.6 on 2025-12-04 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_resume_linkedin_alter_resume_website'),
        ('jobs', '0006_alter_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Note de 1 à 5 étoiles')),
                ('title', models.CharField(help_text="Titre de l'avis", max_length=200)),
                ('comment', models.TextField(help_text='Commentaire détaillé')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags associés à l'avis")),
                ('is_anonymous', models.BooleanField(default=False, help_text='Avis anonyme')),
                ('is_verified', models.BooleanField(default=False, help_text='Avis vérifié (employeur a vraiment recruté)')),
                ('is_approved', models.BooleanField(default=True, help_text='Avis approuvé par modération')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_review', to='jobs.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_reviews', to='accounts.jobseeker')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_reviews', to='accounts.employer')),
            ],
            options={
                'verbose_name': 'Avis candidat',
                'verbose_name_plural': 'Avis candidats',
                'ordering': ['-created_at'],
                'unique_together': {('candidate', 'reviewer', 'application')},
            },
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Note de 1 à 5 étoiles')),
                ('title', models.CharField(help_text="Titre de l'avis", max_length=200)),
                ('comment', models.TextField(help_text='Commentaire détaillé')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags associés à l'avis")),
                ('is_anonymous', models.BooleanField(default=False, help_text='Avis anonyme')),
                ('is_verified', models.BooleanField(default=False, help_text='Avis vérifié (candidat a vraiment postulé)')),
                ('is_approved', models.BooleanField(default=True, help_text='Avis approuvé par modération')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_review', to='jobs.application')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.employer')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to='accounts.jobseeker')),
            ],
            options={
                'verbose_name': 'Avis entreprise',
                'verbose_name_plural': 'Avis entreprises',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'reviewer', 'application')},
            },
        ),
    ]
