# Generated by assistant - add attachment field to Message
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_candidatereview_companyreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(upload_to='message_attachments/', null=True, blank=True),
        ),
    ]
