# Generated by Django 5.2.9 on 2025-12-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_savedjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedJob',
        ),
    ]
