server {
    listen 80;
    server_name tunijob.me www.tunijob.me;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        alias /opt/tunijob/staticfiles/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/opt/tunijob/gunicorn.sock;
    }
}

server {
    listen 443 ssl;
    server_name tunijob.me www.tunijob.me;

    ssl_certificate /etc/letsencrypt/live/tunijob.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tunijob.me/privkey.pem;

    location /static/ {
        alias /opt/tunijob/staticfiles/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/opt/tunijob/gunicorn.sock;
    }
}
